---
name: Pipeline - Commit Lint

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # Docs: https://github.com/actions/checkout/
      - name: 📥 Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
          fetch-depth: 0
      
      # Docs:
      - name: Setup Node
        uses: actions/setup-node@
        with:
          node-version: lts/*
          cache: bun

      - name: Install commitlint
        run: bun install -D @commitlint/cli @w

      - name: Print versions
        run: |
          git --version
          node --version
          bun --version
          bun commitlint --version
      
      - name: Validate curent commit (last commit) with commitlint 
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose
      
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bun commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
    