---
name: Pipeline - Markdown 404

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    # Docs: https://github.com/actions/checkout/
      - name: 📥 Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
          fetch-depth: 0
          
    - name: 'restqa-404-links'
      uses: restqa/404-links@3.1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}